= Geo Assessment - Maersk

Assessment answers for Data Engineer Role at Maersk - little project with scala, apache spark and built using gradle.

== Prerequisites
- https://java.com/en/download/[Java]
- https://gradle.org/[Gradle]
- https://www.scala-lang.org/[Scala]

== Build and Demo process

=== Clone the Repo
`git clone https://github.com/aelkouhen/Geo-Maersk.git`

=== Build
`./gradlew clean build`

=== Run
`./gradlew run`

=== All Together
`./gradlew clean run`

== What the application does?
Take a look at *src->main->scala->com.maersk.geo* directory

We have three Items here:

- The InitSpark trait provides spark context and session variables pre-initialised. It can be extended by any class that wants to run spark code.
This trait has all the code for initialization. I have also suppressed the logging to only error levels for less noise.
- ConversionUtil is a scala object handling the conversion of coordinates from DMS to DD format.
- The main of the application is in the object Geolocalization. In this class, I did:
* Load the provided initial datasets.
* A first left outer join between codeList and countries.
* A second left outer join between the previous result and functions file content.
* Then, I selected relevant columns as required in the email:
`#Country_code | country_name | Location_code | Location_Name | Location_Type | Longitude | Latitude`
* Perform conversion (from DMS to DD) on Latitudes and Longitudes.
* Show the first 10 rows of the final results.
----
+------------+------------+-------------+---------------+--------------------+-------------------+------------------+
|Country_code|Country_name|Location_code|  Location_Name|       Location_Type|          Longitude|          Latitude|
+------------+------------+-------------+---------------+--------------------+-------------------+------------------+
|          AU|   Australia|          ALO|        Adelong|       Road Terminal| -35.31666666666667|148.06666666666666|
|          AU|   Australia|          ANB|     Agnes Bank|       Road Terminal|              -33.6|150.03333333333333|
|          AU|   Australia|          AGW|          Agnew|             Airport|                 NA|                NA|
|          AU|   Australia|          WSY|   Airlie Beach|             Airport|                 NA|                NA|
|          AU|   Australia|          AIR|Airlie Terminal|Port, as defined ...|-21.333333333333332|             115.0|
|          AU|   Australia|          APW|   Airport West|       Road Terminal|-37.733333333333334|            144.05|
|          AU|   Australia|          ALH|         Albany|Port, as defined ...|                 NA|                NA|
|          AU|   Australia|          ALH|         Albany|             Airport|                 NA|                NA|
|          AU|   Australia|          ACK|   Albany Creek|Multimodal Functi...|             -27.35|            152.15|
|          AU|   Australia|          ABO|       Alberton|       Road Terminal|              -27.7|153.08333333333334|
+------------+------------+-------------+---------------+--------------------+-------------------+------------------+
----
* Save the entire results in a csv file.

== Using this Repo
Just import it into your favorite IDE as a gradle project.

== Libraries Included
- Spark - 2.3.0
